EL-4028-FixedHeader
UXAspects/UXAspects pull request #1406
Opened 2020-08-26 11:53 UTC by Sdhilipkumar

#### Checklist

* [ ] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [ ] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [ ] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

#### Description of Proposed Changes
Added new class to achieve fixed header box-shadow.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2020-08-26 11:55 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4028-Fixed-Header) to go ahead and create the build...

2020-08-26 12:25 UTC, donna-marijne requested changes

2020-08-26 12:25 UTC, donna-marijne commented on src/directives/fixed-header-table/fixed-header-table.directive.ts
> +        scrollTop > 0 ? this._hasScrolled = true : this._hasScrolled = false;
This seems like a reasonable approach to me, but I would reverse this statement:
```ts
this._hasScrolled = (scrollTop > 0);
```

2020-08-26 14:03 UTC, donna-marijne commented
Could you convert this to a draft until it is ready please?

2020-08-28 05:47 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4028-Fixed-Header~CI

2020-08-28 06:25 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4028-Fixed-Header

2020-08-28 09:16 UTC, donna-marijne commented
Please fix the PR text. You have a user script to populate it for you.

2020-09-01 15:40 UTC, donna-marijne approved these changes
Changes look good.

2020-09-01 15:42 UTC, ashley-hunter approved these changes
All good, thanks

2020-09-01 15:42 UTC, merged