EL-4087 - Marquee - Wizard Custom Step Content
UXAspects/UXAspects pull request #1412
Opened 2020-09-07 09:43 UTC by ashley-hunter

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4087

#### Description of Proposed Changes

- Adding a `context` input on each step to allow them to provide custom data to the step template
- Adding `index` and `context` properties to the step template context
- Improving documentation with new examples and documenting the new context interface and input
- Added test case
- Fixed an incorrect type used by a splitter event

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4087-Marquee-Wizard-Custom-Content

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4087-Marquee-Wizard-Custom-Content~CI/)

2020-09-07 09:46 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4087-Marquee-Wizard-Custom-Content) to go ahead and create the build...

2020-09-07 09:47 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4087-Marquee-Wizard-Custom-Content~CI

2020-09-07 10:58 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4087-Marquee-Wizard-Custom-Content

2020-09-08 10:20 UTC, donna-marijne requested changes
Thanks, this looks good. Apart from the badge issue, just a couple of documentation suggestions.

2020-09-08 13:11 UTC, ashley-hunter commented
I have made the suggested review fixes and also updated the badge directive to accept numbers as inputs rather than solely strings. I have added test cases for this change also.

2020-09-08 15:31 UTC, donna-marijne requested changes
Thank you, great to get the badge issue taken care of here, it will be a much better experience for anyone trying to use it. There's just one indentation issue in the code snippet.

2020-09-08 15:31 UTC, donna-marijne commented on docs/app/pages/components/components-sections/wizard/marquee-wizard/snippets/step-template.html
> +                    <span class="marquee-wizard-step-title"
Indentation issue here.

2020-09-09 10:43 UTC, ashley-hunter commented
Thanks Donna, indentation should now be corrected

2020-09-09 11:15 UTC, donna-marijne submitted a review, later dismissed
Pushed a fix. @Sdhilipkumar waiting on your review now.

2020-09-09 16:03 UTC, donna-marijne approved these changes

2020-09-10 09:18 UTC, Sdhilipkumar approved these changes
Looks good.

2020-09-10 09:19 UTC, merged