EL-4085 - row selection
UXAspects/UXAspects pull request #1413
Opened 2020-09-09 11:45 UTC by ashley-hunter

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4085

#### Description of Proposed Changes

- Previously the focus state was shown based on whether or not the item that could be tabbed to, rather than if the item was actually focused.
- It is now added when the item is focused and removed when the item is blurred.
- Added unit tests

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4085-Row-Selection

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4085-Row-Selection~CI/)

2020-09-09 11:47 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4085-Row-Selection~CI

2020-09-09 12:22 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4085-Row-Selection

2020-09-10 16:07 UTC, donna-marijne requested changes
Thank you for this, change looks good. Looking at the issue though, I think there is a bit more to this since if you click a table row to select it, it still has a distinct color. Normally we only apply focus styling change to components when they gain focus via the keyboard. Maybe we should check with Roland, but I think that was the intent of raising this issue.

2020-09-10 16:10 UTC, ashley-hunter commented
Ah, ok, I thought the issue was that when the row loses focus the focus styling still remained. I will check with Roland.

2020-09-10 16:52 UTC, merged

2020-09-10 16:54 UTC, ashley-hunter commented
Ok.. for some reason I hit Update from base branch, Github errors out and merges this PR?! So I will raise another PR once I hear the response from Roland