EL-4101 - Wizard-steps-invalid
UXAspects/UXAspects pull request #1419
Opened 2020-09-18 15:01 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4101

#### Description of Proposed Changes

Added stp.visited to class.invalid which fixes the regression in the steps having an invalid appearance before being visited
Added a karma test  to verify that:
invalid appearance is not shown when valid = false and visited = false
Invalid appearance should be shown when valid = false and visited = true

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4101-Wizard-steps-invalid

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4101-Wizard-steps-invalid~CI/)

2020-09-18 15:04 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4101-Wizard-steps-invalid) to go ahead and create the build...

2020-09-18 15:06 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4101-Wizard-steps-invalid~CI

2020-09-18 15:43 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4101-Wizard-steps-invalid

2020-09-18 16:14 UTC, donna-marijne requested changes

2020-09-18 16:14 UTC, donna-marijne commented on src/components/wizard/wizard.component.spec.ts
> +    selector: 'marquee-wizard-validation-appearance',
There's already a text fixture for wizard with validation, I think you can reuse that.

2020-09-21 11:06 UTC, ashley-hunter approved these changes
Looks good to me, thanks

2020-09-21 12:32 UTC, donna-marijne approved these changes
Looks good, thank you Christina.

2020-09-21 12:33 UTC, merged