EL-4100 - Marquee-Wizard-steps
UXAspects/UXAspects pull request #1423
Opened 2020-09-28 09:27 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4100

#### Description of Proposed Changes

Updated the documentation to add the new sequential input in both sites
Added karma tests for the new input 

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4100-Marquee-Wizard-steps

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4100-Marquee-Wizard-steps~CI/)

2020-09-28 09:28 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4100-Marquee-Wizard-steps) to go ahead and create the build...

2020-09-28 09:28 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4100-Marquee-Wizard-steps~CI

2020-09-28 16:55 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4100-Marquee-Wizard-steps

2020-09-29 10:45 UTC, ashley-hunter requested changes
Thanks, just had a few small suggestions

2020-09-29 10:45 UTC, ashley-hunter commented on src/components/marquee-wizard/marquee-wizard.component.spec.ts
> +        it('should allow navigation to any step', async () => {
Could we add some tests to these to cover outputs being emitted, for example, check stepChange, visitedChange and completedChange on the steps are emitted the correct number of times with the correct values,

2020-09-29 10:45 UTC, ashley-hunter commented on src/components/marquee-wizard/marquee-wizard.component.ts
> +    @Input() sequential: boolean = true;
We shouldn't need to add this here is the wizard has it as it will inherit this input

2020-09-29 14:38 UTC, ashley-hunter commented
@DeanHaire is going to finish of the review, thanks

2020-09-29 15:13 UTC, DeanHaire requested changes

2020-09-29 15:13 UTC, DeanHaire commented on src/components/marquee-wizard/marquee-wizard.component.spec.ts
> +            expect(completedChange.calls.all().length).toBe(1);
```suggestion
```
This isn't needed anymore, the line above is sufficient

2020-09-30 08:39 UTC, DeanHaire reviewed
Everything looks good, just one minor formatting issue

2020-09-30 08:39 UTC, DeanHaire commented on src/components/marquee-wizard/marquee-wizard.component.ts
> +        super.gotoStep(step);
This needs to be indented

2020-09-30 08:56 UTC, DeanHaire submitted a review, later dismissed
Looks good, seems to work as expected. Thanks for the changes!

2020-09-30 09:19 UTC, ashley-hunter requested changes

2020-09-30 09:19 UTC, ashley-hunter commented on src/components/marquee-wizard/marquee-wizard.component.ts
> +        if (currentStep != step ) {
Can we use `!==` here and remove the space after `step`.

2020-09-30 09:21 UTC, ashley-hunter approved these changes
All good, thanks

2020-09-30 09:21 UTC, merged