Table Hide Handle
UXAspects/UXAspects pull request #1428
Opened 2020-10-06 09:07 UTC by Sdhilipkumar

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4122

#### Description of Proposed Changes

Added new input property to hide column resizable handle

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2020-10-06 09:10 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4122-Table-Hide-Handle~CI

2020-10-06 09:43 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4122-Table-Hide-Handle

2020-10-07 08:46 UTC, DeanHaire commented on src/components/table/table-column-resize/resizable-table-column.component.spec.ts
> +        fixture.detectChanges();
Is this needed? You're also doing `fixture.detectChanges()` in the `beforeEach`, so I don't think this is needed here or in the test below?

2020-10-07 08:46 UTC, DeanHaire commented on src/components/table/table-column-resize/resizable-table-column.component.spec.ts
> +        expect(inputElement[1].classList.contains('ux-resizable-table-hide-handle')).toBeFalsy();
I think we would be better using `toBe(false)` instead here (and `toBe(true)` in the test below), rather than unnecessarily coercing the value

2020-10-07 12:40 UTC, donna-marijne requested changes
1. Please fix the CI URL in the PR description. There is a userscript to do this for you; if it is not working for you, let me know.

2. It can sometimes be difficult to document or understand configuration properties which are negative because "true" has an implication of something being present, and "false" has an implication of something being absent. Therefore `hidden="true"` is slightly less natural to read than `visible="false"`. So you might want to consider renaming the property to `handleVisible` with a default value of `true`.

3. There are quite a lot of screenshots here which should not have changed and are visually identical. Please check and revert any images with only spurious metadata changes, so that the commit history for those files is clean.

2020-10-07 12:40 UTC, donna-marijne commented on src/components/table/table-column-resize/resizable-table-column.component.html
> +<ng-container *ngIf="!hideHandle">
Is there a problem if you add this condition to the handle element directly? E.g.
```html
<div #handle *ngIf="!disabled && !hideHandle" ...>
```

2020-10-07 12:40 UTC, donna-marijne commented on src/components/table/table-column-resize/resizable-table-column.component.spec.ts
> +    let inputElement: HTMLElement;
Probably should be named `tableHeaderElements`, also the type is incorrect, check https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

2020-10-07 12:40 UTC, donna-marijne commented on src/components/table/table-column-resize/resizable-table-column.component.ts
> +    hideHandle: boolean = false;
Check this item on the tips & tricks page, we should be coercing booleans in new properties:

https://github.houston.softwaregrp.net/caf/ux-aspects-team/wiki/Tips-and-Tricks#coerce-inputs

2020-10-07 12:40 UTC, donna-marijne commented on docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
> +        Can be used to show/hide the resizable column handle.
```suggestion
        Set to true to hide the column drag handle.
```

2020-10-07 12:41 UTC, donna-marijne commented on docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
> +        Can be used to show/hide the resizable column handle.
Disregard this if you are renaming the property as suggested.

2020-10-08 13:17 UTC, donna-marijne requested changes
Changes look good, just a couple of comments for the docs.

2020-10-08 13:17 UTC, donna-marijne commented on docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
> +    <tr uxd-api-property name="handleVisible" type="boolean">
Add `defaultValue="true"` here.

2020-10-08 13:17 UTC, donna-marijne commented on docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
> +        Can be used to show/hide the resizable column handle.
```suggestion
        Specifies if the column drag handle is shown.
```

2020-10-08 13:41 UTC, donna-marijne requested changes

2020-10-08 13:41 UTC, donna-marijne commented on src/components/table/table-column-resize/resizable-table-column.component.ts
> +    @HostBinding('class.ux-resizable-table-hide-handle')
Just noticed that this class binding does not work as intended:
![image](https://user-images.githubusercontent.com/26114101/95466538-58774580-0974-11eb-835f-34ba53fc5ee1.png)

2020-10-09 10:12 UTC, donna-marijne approved these changes
Changes look good, thank you.

2020-10-12 09:20 UTC, DeanHaire approved these changes

2020-10-12 09:20 UTC, merged