EL-4117 - basic-input-controls
UXAspects/UXAspects pull request #1431
Opened 2020-10-12 08:21 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4117

#### Description of Proposed Changes

Added a disabled input & applied some disabled styling to the input

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4117-basic-input-controls

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4117-basic-input-controls~CI/)

2020-10-12 08:22 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4117-basic-input-controls) to go ahead and create the build...

2020-10-12 08:22 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4117-basic-input-controls~CI

2020-10-12 08:48 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4117-basic-input-controls

2020-10-13 11:03 UTC, DeanHaire commented on src/components/slider/slider.component.ts
> +    constructor(colorService: ColorService, private _changeDetectorRef: ChangeDetectorRef, private _changeDetector: ChangeDetectorRef) {
Why is the change detector injected here twice?

2020-10-13 11:04 UTC, donna-marijne requested changes
Thanks Christina, looks like a good start. Bear in mind the usual acceptance criteria when enhancing any existing component.

1. The new property should be documented.
2. We will need test coverage of the new property.
3. When disabled, the slider thumb still has a "pointer" cursor, implying that interaction is permitted. It should be the default cursor.
4. When disabled, the slider thumb should not be able to receive focus.
5. The slider thumb should probably be grayed out in the same way as the track.

https://plnkr.co/edit/hkebVQjLwyn3CHCM

2020-10-13 11:04 UTC, donna-marijne commented on src/components/slider/slider.component.ts
> +        if (!this.disabled) {
Usually with disabled-type properties, we do:

```ts
if (this.disabled) {
  return;
}
```

at the top of the function. This helps reduce nesting, which can be problematic especially in large functions like this.

2020-10-13 11:04 UTC, donna-marijne commented on src/components/slider/slider.component.html
> +     [class.disabled]="disabled"
This should not be needed since the parent element has a disabled class as well, you can use that in the selector instead.

2020-10-19 08:37 UTC, donna-marijne requested changes

2020-10-26 08:41 UTC, donna-marijne approved these changes

2020-10-26 09:41 UTC, DeanHaire approved these changes

2020-10-26 10:12 UTC, merged