EL-4057 - Dashboard Layout not getting updated when using OnPush
UXAspects/UXAspects pull request #1433
Opened 2020-10-12 16:33 UTC by DeanHaire

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4057

#### Description of Proposed Changes

- `renderDashboard()` when a new layout value is emitted
- Add testpage for layout which uses the async pipe

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4057-dashboard-layout

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4057-dashboard-layout~CI/)

2020-10-12 16:34 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4057-dashboard-layout) to go ahead and create the build...

2020-10-12 16:35 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4057-dashboard-layout~CI

2020-10-12 17:02 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4057-dashboard-layout

2020-10-13 09:05 UTC, donna-marijne requested changes
Fix looks good, seems like some mistakenly removed tests here though?

2020-10-13 09:12 UTC, DeanHaire commented on e2e/tests/components/dashboard/dashboard.e2e-spec.ts
> -    it('should not change the order of widgets when moving from regular to stacked mode', async () => {
These tests seemed to be duplicates of the test above this, unless there's some minor difference that I've missed. If you view the whole file you can see that I've left one copy of this test.

2020-10-13 09:15 UTC, donna-marijne commented on e2e/tests/components/dashboard/dashboard.e2e-spec.ts
> -    it('should not change the order of widgets when moving from regular to stacked mode', async () => {
Ah, I see, no problem then!

2020-10-13 13:12 UTC, donna-marijne approved these changes
Looks good, thank you.

2020-10-13 13:12 UTC, merged