EL-4138 - Hierarchy Bar Long Label Issue
UXAspects/UXAspects pull request #1437
Opened 2020-10-16 15:22 UTC by DeanHaire

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4138

#### Description of Proposed Changes

- Removes gap between 1st and 2nd hierarchy bar nodes
- Also fixes EL-4137

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4138-hierarchy-bar-label

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4138-hierarchy-bar-label~CI/)

2020-10-16 15:25 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4138-hierarchy-bar-label) to go ahead and create the build...

2020-10-16 15:25 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4138-hierarchy-bar-label~CI

2020-10-19 14:49 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4138-hierarchy-bar-label

2020-10-20 08:35 UTC, cmallon367 submitted a review, later dismissed
Looks good the fix works well

2020-10-20 10:41 UTC, donna-marijne requested changes
Change looks good, I have one suggestion regarding the test.

2020-10-20 14:45 UTC, donna-marijne approved these changes
Looks good, thank you.

2020-10-20 14:45 UTC, merged