EL-4141 - date time picker
UXAspects/UXAspects pull request #1438
Opened 2020-10-19 16:43 UTC by Sdhilipkumar

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4141

#### Description of Proposed Changes

Added a spec for removing horizontal line when select next month

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4141-date-time-picker

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4141-date-time-picker~CI/)

2020-10-19 16:46 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4141-date-time-picker) to go ahead and create the build...

2020-10-19 16:48 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4141-date-time-picker~CI

2020-10-19 18:04 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4141-date-time-picker

2020-10-20 09:33 UTC, donna-marijne requested changes

2020-10-20 09:33 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +        let date = await page.getDate('31');
Should be `const`.

2020-10-20 09:33 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +        expect(await imageCompare('date-picker-horizontal-line-removed')).toBe(0);
The screenshot name should describe the use case, not the bug that you fixed. In this case, the Keppel theme has no horizontal line to remove so it doesn't make sense. In this case  `date-picker-adjacent-month-selection` might be appropriate.

2020-10-20 09:33 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +        await page.nextDate.click();
Here you should assert that the selected class is applied to the button of the 31st in the adjacent month.

2020-10-20 09:33 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +    it('should not display horizontal line when select adjacent month', async () => {
Here again the reference to the horizontal line should be removed, because it is theme specific.

2020-10-21 15:19 UTC, donna-marijne requested changes

2020-10-21 15:19 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +        expect(classes.indexOf('active')).toBeGreaterThan(-1);
This should be after the `page.nextDate.click()` line, where I put the previous comment.

2020-10-22 08:25 UTC, donna-marijne requested changes

2020-10-22 08:25 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +        const classes = await date.getAttribute('class');
You need to move this too.

2020-10-22 10:34 UTC, donna-marijne commented on e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
> +        const classes = await date.getAttribute('class');
Yes, the markup has changed so you have to fetch the new button element and test it.

2020-10-22 19:09 UTC, donna-marijne approved these changes
Changes look good, thank you Sasi.

2020-10-23 05:13 UTC, naveenk550 approved these changes
Looks good. Thank you.

2020-10-23 05:14 UTC, merged