EL-4157 - Input-Dropdown-input-field
UXAspects/UXAspects pull request #1444
Opened 2020-10-30 09:31 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4157

#### Description of Proposed Changes

Removed filter focus from the dropdown menu so that it no longer receives focus when opened programmatically  
#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4157-Input-Dropdown-input-field

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4157-Input-Dropdown-input-field~CI/)

2020-10-30 09:40 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4157-Input-Dropdown-input-field~CI

2020-10-30 10:06 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4157-Input-Dropdown-input-field

2020-10-30 11:26 UTC, DeanHaire commented
I'm wondering would it be possible to test this via an e2e test? Possibly by using `await browser.driver.switchTo().activeElement()` to get the currently focused element you could assert that this element isn't the input field?

Also, could you update the title of the PR to better describe the issue so that if someone is looking through the commits they can get an understanding of the purpose of this PR without needing to open and read through it.

2020-10-30 11:32 UTC, cmallon367 commented
I'm assuming the reason we didn't use the e2e tests is because there wasn't an issue on our end it became apparent whenever the user was running cypress

2020-10-30 11:34 UTC, donna-marijne commented
If it is possible to add test coverage, you definitely should.

2020-10-30 11:40 UTC, DeanHaire commented
> I'm assuming the reason we didn't use the e2e tests is because there wasn't an issue on our end it became apparent whenever the user was running cypress

Yes, but it'd be good to cover this case if we can to prevent a regression in future. There's a couple of examples of using the approach I suggested such as `hasFocus` in `column-picker.po.spec.ts` and in the [sliders tests](https://github.com/UXAspects/UXAspects/blob/a14387516089e28b647f3bd451051062810b6fbb/e2e/tests/components/sliders/sliders.e2e-spec.ts#L373) if that's helpful

2020-10-30 15:39 UTC, DeanHaire approved these changes

2020-11-03 08:47 UTC, tobias-schreiner commented
There are two issues I can see with this approach:

1. The filter field is never focused when the drop-down is opened. This degrades the usability of the component for interactive use.

2. Using only the keyboard, I cannot access the filter field and also the content of the drop-down anymore. So the accessibility of the component is broken.

I have to admit, though, that I have no access to your ticketing system, so I don't know the background for this change.

2020-11-03 09:12 UTC, andyreidz commented
![image](https://user-images.githubusercontent.com/18459684/97967081-a4bb7700-1db4-11eb-9862-8870a4ac23aa.png)

2020-11-03 10:01 UTC, donna-marijne commented
So it seems like `this._focusFilter` should still be called in every case except when the menu has been opened by setting `dropdownOpen` to true. Checking the value of `dropdownOpen` at the start of `onMenuOpen` might do the trick.

2020-11-03 14:18 UTC, donna-marijne requested changes
Following Tobias' feedback, please also set up test coverage to make sure that the input field is correctly focused when the dropdown is opened via click.

2020-11-03 14:18 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.spec.ts
> +        expect(document.activeElement).not.toBe(input);
I reverted your fix below and ran this test and it still passed. Could you look into another way to verify this, and check that it is effective?

2020-11-03 14:18 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.ts
> -            this.dropdownOpenChange.emit(this.dropdownOpen);
This is also called by a `focus` handler in the template, so I don't think this is the right fix. You might be able to move `this._focusFilter()` down a couple of lines to solve this problem.

2020-11-03 16:46 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.spec.ts
> +        expect(document.activeElement).not.toBe(input);
Ignore this, I made a mistake.

2020-11-04 10:04 UTC, donna-marijne requested changes

2020-11-04 10:04 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.spec.ts
> +        expect(component.filterInputElement.nativeElement.focus).toHaveBeenCalled();
This should be `expect(document.activeElement).toBe(input);` I think (the opposite of your check in the other test).

2020-11-04 10:04 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.spec.ts
> +        let trigger = document.querySelector('button.form-control') as HTMLButtonElement;
Should be `const`.

2020-11-04 10:04 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.ts
> +            this._focusFilter();
Move this below the next line as well, I think.

2020-11-04 15:22 UTC, DeanHaire approved these changes

2020-11-04 15:32 UTC, donna-marijne approved these changes
Looks good, thank you.

2020-11-04 15:32 UTC, merged