EL-3341 - List-3rd-party dependencies
UXAspects/UXAspects pull request #1464
Opened 2020-12-15 07:49 UTC by Sdhilipkumar

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-3341

#### Description of Proposed Changes

I have listed the 3rd party dependencies which are required to install manually.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3341-list-3rd-party-components

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3341-list-3rd-party-components~CI/)

2020-12-15 07:52 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-3341-list-3rd-party-components) to go ahead and create the build...

2020-12-15 07:57 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-3341-list-3rd-party-components~CI

2020-12-15 09:12 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3341-list-3rd-party-components

2020-12-18 10:37 UTC, DeanHaire commented on docs/app/pages/components/components-sections/file-upload/file-upload/file-upload.component.html
> +</blockquote>
I'm wondering would it be better to have these notes at the top of each of their sections so it's the first thing (except the actual example componenet) that a reader would see? Although for the file upload that would mean having two notes side by side which would look a bit weird so I'm not sure how you'd get around that. Maybe combine the notes into one? What do you think?

2020-12-18 10:41 UTC, DeanHaire commented on docs/app/pages/components/components-sections/file-upload/file-upload/file-upload.component.html
> +        Refer to <a href="https://valor-software.com/ng2-file-upload/" target="_blank">ng2-file-upload</a> for complete documentation on this component.
```suggestion
        Refer to <a href="https://valor-software.com/ng2-file-upload/" target="_blank" rel="noopener">ng2-file-upload</a> for complete documentation on this component.
```
https://web.dev/external-anchors-use-rel-noopener/

2020-12-18 14:21 UTC, DeanHaire approved these changes

2021-01-04 09:46 UTC, donna-marijne requested changes
Please create a downstream build for this branch.

2021-01-04 09:46 UTC, donna-marijne commented on docs/app/pages/components/components-sections/file-upload/file-upload/file-upload.component.html
> +    <p><b>Note:</b> If you are using this component in your application, you will need to install <strong>ng2-file-upload</strong> manually
```suggestion
    <p><b>Note:</b> If you are using this component in your application, you will need to install <strong>ng2-file-upload</strong> manually.
```

2021-01-04 09:46 UTC, donna-marijne commented on docs/app/pages/components/components-sections/file-upload/file-upload/file-upload.component.html
> +        ( Refer to <a href="https://valor-software.com/ng2-file-upload/">ng2-file-upload</a> for complete documentation on this component.)
```suggestion
        Refer to <a href="https://valor-software.com/ng2-file-upload/">ng2-file-upload</a> for complete documentation on this component.
```

The two notes you have added should be consistent with each other.

2021-01-04 09:46 UTC, donna-marijne commented on src/package.json
> -    "ngx-mask": "^2.5.3",
Because this is a breaking change, you should update BREAKING_CHANGES.md in both repositories with details on how to upgrade.

2021-01-05 12:15 UTC, Sdhilipkumar commented
As there is a conflict with the master branch hence I am closing this PR.

2021-01-05 12:15 UTC, closed without merging