EL-4074 - Angular tree package deprecated
UXAspects/UXAspects pull request #1465
Opened 2020-12-15 10:16 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4074

#### Description of Proposed Changes

Updated to the new package @circlon/angular-tree-component 
Removed the inappropriate importing of the css being used by the tree component
#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4074-Angular-tree-package-deprecated

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4074-Angular-tree-package-deprecated~CI/)

2020-12-15 10:19 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4074-Angular-tree-package-deprecated) to go ahead and create the build...

2020-12-15 10:21 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4074-Angular-tree-package-deprecated~CI

2020-12-15 10:33 UTC, cmallon367 commented
Just looking for feedback to make sure I'm going about this the correct way

2020-12-15 10:51 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4074-Angular-tree-package-deprecated

2020-12-16 12:16 UTC, donna-marijne requested changes
Also need to update the library peer dependencies, in src/package.json.

2020-12-16 15:35 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4074-Angular-tree-package-deprecated

2020-12-18 14:36 UTC, DeanHaire approved these changes

2021-01-04 10:16 UTC, donna-marijne requested changes

2021-01-04 10:19 UTC, donna-marijne requested changes

2021-01-04 10:19 UTC, donna-marijne commented on BREAKING_CHANGES.md
> +* Angular tree component is now deprecated.
```suggestion
* The package for `angular-tree-component` has been renamed.
```

2021-01-04 13:49 UTC, donna-marijne approved these changes
Looks good, thank you.

2021-01-04 14:04 UTC, DeanHaire approved these changes

2021-01-04 14:04 UTC, merged