EL-4055 - Tooltip Fallback Positioning
UXAspects/UXAspects pull request #1471
Opened 2021-01-13 14:48 UTC by DeanHaire

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4055

#### Description of Proposed Changes

- Use sensible fallback position when tooltip is off screen
- Add `fallbackPlacement` input to allow a custom fallback position

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4055-fallback-tooltips

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4055-fallback-tooltips~CI/)

2021-01-13 14:49 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4055-fallback-tooltips~CI

2021-01-13 14:49 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4055-fallback-tooltips~CI

2021-01-13 17:12 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4055-fallback-tooltips

2021-01-14 13:18 UTC, donna-marijne requested changes
Looks like it works well, thank you. I set up this plunker to test all of the positions, and I think it would be worth having full coverage similar to this in the e2e tests.

https://plnkr.co/edit/nYjJIQBKMse0jha3

For this, a new test page would make sense.

2021-01-14 14:25 UTC, DeanHaire commented on docs/app/pages/components/components-sections/popover/popover/popover.component.html
> +    <tr uxd-api-property name="fallbackPlacement" type="string">
I'll make the same change for the normal `placement` input as well since it's currently using `string` too

2021-01-15 13:38 UTC, donna-marijne approved these changes
Looks good, thank you.

2021-01-15 13:38 UTC, merged