EL-4189-Support the `required` attribute in all input controls
UXAspects/UXAspects pull request #1483
Opened 2021-02-05 13:25 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4189

#### Description of Proposed Changes

Added the required input and updated the documentation
Added karma test to verify that the required attribute is set

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4189-Required-attribute-on-input-controls

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4189-Required-attribute-on-input-controls~CI/)

2021-02-05 13:27 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4189-Required-attribute-on-input-controls~CI

2021-02-05 13:58 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4189-Required-attribute-on-input-controls

2021-02-05 17:03 UTC, DeanHaire submitted a review, later dismissed

2021-02-05 17:56 UTC, donna-marijne requested changes
Thanks for this. I just wanted to check, are you verifying the changes with a screen reader?

I think in all cases you can remove the `aria-required` attribute since it's redundant. I also don't think you need to add the new test components, the attribute can be added to existing test cases without disrupting them.

2021-02-05 17:56 UTC, donna-marijne commented on src/components/checkbox/checkbox.component.html
> +               [attr.aria-required]="required"
This should not be necessary, check the first note here:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute

2021-02-05 17:56 UTC, donna-marijne commented on src/components/input-dropdown/input-dropdown.component.html
> +                    [attr.aria-required]="required"
This doesn't represent the value of the control, it's a filter field and should never be marked as required.

2021-02-05 17:56 UTC, donna-marijne commented on src/components/checkbox/checkbox.component.spec.ts
> +export class CheckboxRequiredTestComponent {
I think you can safely merge the `required` property into one of the existing test components, like you did with the number picker.

2021-02-05 17:56 UTC, donna-marijne commented on src/components/select/select.component.html
> +    [attr.aria-required]="required"
I don't think this does anything because the component wrapper doesn't receive focus. Did you mean to use the `required` input that you added?

2021-02-09 12:32 UTC, donna-marijne requested changes

2021-02-09 12:32 UTC, donna-marijne commented on docs/app/pages/components/components-sections/input-controls/toggleswitch/toggleswitch.component.html
> +      </tr>
Indentation.

2021-02-09 12:32 UTC, donna-marijne commented on src/components/checkbox/checkbox.component.spec.ts
> +        await fixture.whenStable();
I don't think that whenStable is needed here or for any of these tests, please confirm.

2021-02-09 17:52 UTC, donna-marijne requested changes
Last thing from me, sorry for not noticing this before. In all cases `document.querySelectorAll` should be `nativeElement.querySelector`. Make sure to use `querySelector` when you are only expecting one result so that you don't have to index an array.

2021-02-10 11:51 UTC, DeanHaire approved these changes

2021-02-10 11:56 UTC, donna-marijne approved these changes
Great, thank you.

2021-02-10 11:57 UTC, merged