EL-4189-Support-the-required-attribute-toggle-switch
UXAspects/UXAspects pull request #1487
Opened 2021-02-12 10:31 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4189

#### Description of Proposed Changes

Removed role to allow required attribute on toggle switch when using screen reader

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Support-the-required-attribute-toggle-switch

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~Support-the-required-attribute-toggle-switch~CI/)

2021-02-12 10:34 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~Support-the-required-attribute-toggle-switch~CI

2021-02-12 11:29 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Support-the-required-attribute-toggle-switch

2021-02-12 16:32 UTC, donna-marijne requested changes
It doesn't seem to make any difference. Is the build up to date with your changes? Which screen reader did you test with?

2021-02-12 17:01 UTC, cmallon367 commented
I was using Narrator its built in screen reader to windows & it was working fine with that

2021-02-15 10:53 UTC, DeanHaire approved these changes
Seems to now be working with the narrator screen reader I used for QA

2021-02-15 10:56 UTC, donna-marijne approved these changes

2021-02-15 10:56 UTC, merged