Remove whitespace between btn-group class and not selector
UXAspects/UXAspects pull request #1496
Opened 2021-03-04 09:58 UTC by pamadei

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
There is a whitespace between the `btn-group` class and the `:not` selector in one of the buttons styles. This is causing the margin-bottom and padding styles to be applied incorrectly to the `btn-group`. 
Here the plunker which showcases the issue: https://plnkr.co/edit/vxWYlrvBAcAMy78Y.

#### Description of Proposed Changes
* Add missing `&` before the `:not` selector.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_fix-btn-group-styles

#### Downstream Build(s)

2021-03-04 10:00 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~fix-btn-group-styles~CI

2021-03-04 10:37 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_fix-btn-group-styles

2021-03-05 10:53 UTC, donna-marijne requested changes
I think this is a misunderstanding, I'm quite sure that the space is not there by accident. The reason being that `.btn` is always a child of `.btn-group`, so the rule as you have written it won't match anything.

Changing this rule will break layouts, due to removal of the bottom margin, so we cannot make this change in a minor release.

In your plunker you have a custom set of styles which reduce the height of the buttons. This is why the alignment is broken - the stylesheet is designed for specific button height and padding values.

The correct way to make a small set of buttons is to use the `btn-sm` class. To support this we would have to modify this rule, e.g.:

```css
.btn-group :not(.dropdown-toggle:first-child).btn.btn-sm {
  padding: 4px 8px;
}
```

Here's an example. Let me know what you think.

https://plnkr.co/edit/8kO2x8Cq98eyZ3OB

2021-03-05 15:15 UTC, pamadei-mf commented
> I think this is a misunderstanding, I'm quite sure that the space is not there by accident. The reason being that `.btn` is always a child of `.btn-group`, so the rule as you have written it won't match anything.
> 
> Changing this rule will break layouts, due to removal of the bottom margin, so we cannot make this change in a minor release.
> 
> In your plunker you have a custom set of styles which reduce the height of the buttons. This is why the alignment is broken - the stylesheet is designed for specific button height and padding values.
> 
> The correct way to make a small set of buttons is to use the `btn-sm` class. To support this we would have to modify this rule, e.g.:
> 
> ```css
> .btn-group :not(.dropdown-toggle:first-child).btn.btn-sm {
>   padding: 4px 8px;
> }
> ```
> 
> Here's an example. Let me know what you think.
> 
> https://plnkr.co/edit/8kO2x8Cq98eyZ3OB

Thank you Donna for the explanation. I understand what you mean. I have added a `padding` to the `btn-sm`, so the small buttons are displayed correctly. Let me know what do you think.

2021-03-08 15:08 UTC, donna-marijne approved these changes
Great - thank you!

2021-03-08 15:08 UTC, merged