EL-4213 - automatic closing dropdown panel
UXAspects/UXAspects pull request #1502
Opened 2021-03-11 06:31 UTC by Sdhilipkumar

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4213

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4213-automatic-closing-dropdown-panel

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4213-automatic-closing-dropdown-panel~CI/)

2021-03-11 06:34 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4213-automatic-closing-dropdown-panel) to go ahead and create the build...

2021-03-11 12:20 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4213-automatic-closing-dropdown-panel~CI

2021-03-11 12:48 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4213-automatic-closing-dropdown-panel

2021-03-12 10:37 UTC, DeanHaire commented on e2e/tests/components/select/standard/select.po.spec.ts
> +    checkboxAutoDropdownClose = element(by.id('checkbox6'));
Can you move this below `checkbox5`?

2021-03-12 13:40 UTC, donna-marijne requested changes
Thanks, just a couple of general comments:

1. There's no reason for this setting to be restricted to multiple select, so let's have it apply in single select as well.
2. You've added a new input to Tag Input, so that should be documented.

2021-03-15 14:40 UTC, donna-marijne requested changes
Looks good, just missing test coverage of the new input when multiple=false.

2021-03-16 09:54 UTC, donna-marijne approved these changes
Looks good.

2021-03-16 10:11 UTC, DeanHaire approved these changes

2021-03-16 10:11 UTC, merged