EL-4232 - Option to prevent menu from closing on item click/enter
UXAspects/UXAspects pull request #1527
Opened 2021-04-26 14:59 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4232

#### Description of Proposed Changes

Added new input 'closeOnSelect' and updated the new input on the documentation site
#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4232-prevent-menu-close-on-item-click

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4232-prevent-menu-close-on-item-click~CI/)

2021-04-26 15:02 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4232-prevent-menu-close-on-item-click~CI

2021-04-26 15:43 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4232-prevent-menu-close-on-item-click

2021-04-27 13:40 UTC, JonathanToddMF requested changes
Looks good and has solved the issue although there appears to be a regression

I have added the new input to the `Mark As` menu item and its submenus `Pending`, `Escalated `and `Closed` in the following plunker - https://plnkr.co/edit/ZnI7oNcL285BmI5C

You can see that the submenu does not close when the options are selected.

However, when using `closeOnSelect` with the `activate` output it no longer seems to emit when it is clicked on.  If you check the plunker I have provided, removing the `closeOnSelect` causes the activate to work as intended.

2021-04-27 13:40 UTC, JonathanToddMF commented on src/components/menu/menu-item/menu-item.component.ts
>              this.activate.emit(event);
The above could be the cause of this, we are stopping the activate from being emitted here. Maybe we could have another if statement just for `closeOnSelect` which stops the `this.onClick$.next` but keeps the `this.closeOnSelect`?

2021-04-29 10:11 UTC, JonathanToddMF submitted a review, later dismissed
Looks good Christina, the `activate` output is now working with `closeOnSelect`

Fix detailed here - https://plnkr.co/edit/ZnI7oNcL285BmI5C

You can see the activate output working in the console. Note Mark As > Closed does not have the `closeOnSelect` applied to test this still works without it.

2021-04-30 09:41 UTC, donna-marijne requested changes
Can you add some tests?

2021-05-04 11:14 UTC, donna-marijne requested changes
Looks good, I just noticed one error in the documentation.

2021-05-04 11:14 UTC, donna-marijne commented on docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.html
> +        Determine if the menu should close on click of the submenu.
```suggestion
        Determine if the menu should close on click of the menu item.
```

2021-05-04 12:26 UTC, donna-marijne approved these changes
Looks good, thank you.

2021-05-04 12:27 UTC, donna-marijne submitted a review, later dismissed
Looks good, thank you.

2021-05-05 09:23 UTC, JonathanToddMF submitted a review, later dismissed
Tests look good, QA to follow

2021-05-05 09:41 UTC, JonathanToddMF commented
QA: One minor issue found

Following plunker - https://plnkr.co/edit/pCgTHupy4op8zOky - shows the new `closeOnSelect` input on the `Pending` and `Escalated` sub menu items inside `Mark as`. Clicking on these keeps the menu open and does not close it as required. `Closed` inside `Mark as` does not have this new input and closes correctly.

Defects:
When navigating the menu with the keyboard controls pressing enter on one of the items that has `closeOnSelect` set as true causes the `activate` output to trigger twice

2021-05-06 15:21 UTC, JonathanToddMF requested changes
Hi Christina, all looks good with this although I would combine the if statement you've added.

2021-05-06 15:21 UTC, JonathanToddMF commented on src/components/menu/menu-item/menu-item.component.ts
> +        }
We should probably combine these if statements

`if (event instanceof MouseEvent && event.screenX === 0 && event.screenY === 0) {
    return;
}`

2021-05-07 13:33 UTC, JonathanToddMF approved these changes
preventDefault is definitely a lot clearer. Approved thanks!

2021-05-07 14:52 UTC, JonathanToddMF commented
Qa complete and working

2021-05-07 14:59 UTC, JonathanToddMF commented
QA complete and tested in the following browsers - Chrome, Firefox, Edge and IE11

Following plunker - https://plnkr.co/edit/pCgTHupy4op8zOky - shows the new closeOnSelect input on the Pending and Escalated sub menu items inside Mark as. Clicking on these keeps the menu open and does not close it as required. Closed inside Mark as does not have this new input and closes correctly.

Using keyboard controls no longer emits the activate output twice.

Awaiting acceptance @Roland-Penny

2021-05-10 10:56 UTC, Roland-Penny approved these changes
Looks good.

2021-05-10 10:59 UTC, merged