EL-4218 - Select custom heading options
UXAspects/UXAspects pull request #1532
Opened 2021-05-04 09:47 UTC by cmallon367

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4218

#### Description of Proposed Changes

Added new template bindings
Updated the documentation to include new template bindings
Added additional test coverage and screenshot to show the custom headings
#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4218-select-custom-headings

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4218-select-custom-headings~CI/)

2021-05-04 09:48 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4218-select-custom-headings~CI

2021-05-04 12:02 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4218-select-custom-headings

2021-05-05 09:19 UTC, donna-marijne requested changes
It doesn't look like the options heading shows when there aren't any recent options?

https://plnkr.co/edit/scgH5E6aXtnZl57N

Please take time to look over your changes and make sure that they work before submitting for review. Seeing a lot of mistakes from copy/paste in here.

2021-05-05 09:19 UTC, donna-marijne commented on src/components/select/select.component.ts
> +    @Input() headingTemplate: TemplateRef<any>;
Don't use `any`.

2021-05-05 09:19 UTC, donna-marijne commented on src/components/typeahead/typeahead.component.html
> +<ng-template #defaultHeadingTemplate></ng-template>
These are empty, so remove them.

2021-05-05 09:19 UTC, donna-marijne commented on src/components/typeahead/typeahead.component.less
> +    .ux-typeahead-recent-options-heading {
This isn't used.

2021-05-05 09:19 UTC, donna-marijne commented on docs/app/pages/components/components-sections/select/select/select.component.html
> +            The following code snippet shows how to use a custom template to display an icon alongside the tag text:
This description is incorrect.

2021-05-05 09:19 UTC, donna-marijne commented on docs/app/pages/components/components-sections/select/select/select.component.html
> +    <tr uxd-api-property name="headingTemplate" type="TemplateRef">
```suggestion
    <tr uxd-api-property name="optionsHeadingTemplate" type="TemplateRef">
```
`headingTemplate` is too generic a name for a component like this.

2021-05-05 09:19 UTC, donna-marijne commented on e2e/tests/components/select/custom-heading/select-custom-heading.e2e-spec.ts
> +    });
You should add coverage for when there are no recent options selected.

2021-05-10 08:17 UTC, donna-marijne requested changes
Looks like the divider is broken:
![image](https://user-images.githubusercontent.com/26114101/117627292-ecf69000-b16f-11eb-987e-aa49548ccfea.png)

https://plnkr.co/edit/yhiijelTSdZSqxws

Check the suggestion from the previous review.

The new inputs for typeahead have not been documented:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4218-select-custom-headings/#/components/input-controls#typeahead

2021-05-10 08:17 UTC, donna-marijne commented on e2e/pages/app/select/custom-heading/select-custom-heading.testpage.component.ts
> +    dataSet = new BehaviorSubject<string>('strings');
Can you remove this unused code?

2021-05-10 08:17 UTC, donna-marijne commented on e2e/tests/components/select/custom-heading/select-custom-heading.po.spec.ts
> +export class SelectCustomHeadingPage {
Can you remove the unused code in this class? Additionally, all functions should have a return type.

2021-05-10 08:17 UTC, donna-marijne commented on e2e/tests/components/select/custom-heading/select-custom-heading.po.spec.ts
> +    nodes = element(by.id('Nodes'));
```suggestion
    optionsHeading = element(by.id('Nodes'));
```

2021-05-10 08:17 UTC, donna-marijne commented on e2e/pages/app/select/custom-heading/select-custom-heading.testpage.component.html
> +    <div id="Nodes">Nodes</div>
```suggestion
    <div id="options-header">Nodes</div>
```
Try to use meaningful IDs/variable names.

2021-05-10 08:17 UTC, donna-marijne commented on e2e/pages/app/select/custom-heading/select-custom-heading.testpage.component.html
> +    <div id="recentNodes">Recent Nodes</div>
```suggestion
    <div id="recent-options-header">Recent Nodes</div>
```

2021-05-10 08:17 UTC, donna-marijne commented on src/components/typeahead/typeahead.component.less
> +        .ux-typeahead-recent-divider {
You haven't used this class.

2021-05-11 14:27 UTC, JonathanToddMF submitted a review, later dismissed
Thanks Christina looks good!

2021-05-12 12:02 UTC, donna-marijne approved these changes
This should be good for QA now.

2021-05-12 14:48 UTC, JonathanToddMF commented
QA Complete - Tested on Chrome, Firefox, Edge and IE11

Following plunker - https://plnkr.co/edit/DAPfEATGqibo6h0P shows the recent options heading and options heading.
Note: Styling of these headings would be up to the implementer. I have added some padding to the headings.

Awaiting acceptance @Roland-Penny

2021-05-12 15:14 UTC, Roland-Penny approved these changes
Accepted

2021-05-14 09:48 UTC, merged