EL-4146: Color Service Aliases
UXAspects/UXAspects pull request #1534
Opened 2021-05-06 12:09 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-4146

#### Description of Proposed Changes
1. Updated color

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2021-05-06 12:10 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4146-color-service-aliases) to go ahead and create the build...

2021-05-06 12:30 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4146-color-service-aliases~CI

2021-05-06 12:59 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4146-color-service-aliases

2021-05-07 10:30 UTC, cmallon367 commented
You forgot to fill in the downstream build part of the PR

2021-05-07 15:13 UTC, donna-marijne commented
I strongly suggest using the [UX Aspects userscripts](https://github.houston.softwaregrp.net/caf/ux-aspects-team/tree/master/userscripts) - save yourself a lot of typing when making a pull request.

2021-05-07 15:28 UTC, donna-marijne requested changes
This looks fine, I think there's some redundant code though.

2021-05-07 15:28 UTC, donna-marijne commented on src/services/color/color.service.spec.ts
> +    service.getColorSet();
I don't think this line is needed.

2021-05-10 11:04 UTC, donna-marijne requested changes

2021-05-10 11:04 UTC, donna-marijne commented on src/services/color/color-sets/micro-focus-color-set.ts
> +    'info': '00abf3',
```suggestion
    'info': '#00abf3',
```
Maybe should fix `critical` there as well.

2021-05-11 10:47 UTC, donna-marijne approved these changes
Thank you, it looks good.

2021-05-14 09:02 UTC, merged