El 4236 dashboard option prevent widgets moved
UXAspects/UXAspects pull request #1540
Opened 2021-05-20 09:15 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-4236

#### Description of Proposed Changes
WIP

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2021-05-20 14:52 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4236-dashboard-option-prevent-widgets-moved~CI

2021-05-25 09:35 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4236-dashboard-option-prevent-widgets-moved

2021-05-27 15:36 UTC, donna-marijne requested changes
Thanks, unfortunately looks like there are several issues here.

1. Widgets can reset to the wrong place after being dragged over an immovable widget (including stacking).
    https://plnkr.co/edit/tQhYF49H2uKbKHqy
    [![Image from Gyazo](https://i.gyazo.com/6c9d0fb8b9d3075fd8d257bd39df0cab.gif)](https://gyazo.com/6c9d0fb8b9d3075fd8d257bd39df0cab)

2. Widget can be stacked on an immovable widget via the keyboard.
    https://plnkr.co/edit/tQhYF49H2uKbKHqy
    [![Image from Gyazo](https://i.gyazo.com/0b5338dcb58deddc2e92476fcd3f2302.gif)](https://gyazo.com/0b5338dcb58deddc2e92476fcd3f2302)

3. Widget can be stacked on an immovable widget via drag & drop.
    https://plnkr.co/edit/mRTJSAxcGPmAKiDX
    [![Image from Gyazo](https://i.gyazo.com/952dc20758878a0932c7653f2a086369.gif)](https://gyazo.com/952dc20758878a0932c7653f2a086369)

4. Widget with canMove=false can be moved by another widget.
    https://plnkr.co/edit/mRTJSAxcGPmAKiDX
    [![Image from Gyazo](https://i.gyazo.com/1f7cd8238a250529bfcf106bd2afe976.gif)](https://gyazo.com/1f7cd8238a250529bfcf106bd2afe976)

2021-05-27 15:36 UTC, donna-marijne commented on src/components/dashboard/widget/dashboard-widget.component.ts
> +    @Input() canMove: boolean = true;
This should be coerced to boolean, see https://github.houston.softwaregrp.net/caf/ux-aspects-team/wiki/Tips-and-tricks#coerce-inputs.

2021-06-02 13:22 UTC, donna-marijne requested changes
Thanks, seems to work well except for keyboard usage which still has the same issue with overlapping:
https://plnkr.co/edit/evFq3QUVslpVZePE?preview
[![Image from Gyazo](https://i.gyazo.com/afeea3cf7784aff14955c3346b912c08.gif)](https://gyazo.com/afeea3cf7784aff14955c3346b912c08)

Test coverage should be added to ensure that this does not happen.

Take care of code formatting as well.

2021-06-02 13:22 UTC, donna-marijne commented on docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.html
> +    <tr uxd-api-property name="pinned" type="boolean" defaultValue="false">Defines whether or not this widget is pinned to the top row and whether it can be moved from its location. When set to <code
As usual, please break long lines. I would not expect `row` and `col` to have to be specified for this to work. `col` should implicitly be 0 if it is pinned.

2021-06-02 13:22 UTC, donna-marijne commented on e2e/pages/app/dashboard/pinned-layout/pinned-layout.testpage.component.html
> +                  <div class="widget-content"
Indentation issue.

2021-06-02 13:22 UTC, donna-marijne commented on e2e/pages/app/dashboard/pinned-layout/pinned-layout.testpage.component.html
> +                  pinned>
```suggestion
                  pinned="true">
```

2021-06-02 13:22 UTC, donna-marijne commented on e2e/pages/app/dashboard/pinned-layout/pinned-layout.testpage.component.html
> +              <ux-dashboard-widget id="alert-widget" name="Alert" [col]="undefined" [row]="undefined">
```suggestion
              <ux-dashboard-widget id="alert-widget" name="Alert">
```

2021-06-02 13:22 UTC, donna-marijne commented on src/components/dashboard/widget/dashboard-widget.component.ts
> +        this._pinned = coerceBooleanProperty(pinned);
You missed the `ngAcceptInputType_` property.

2021-06-02 13:22 UTC, donna-marijne commented on src/components/dashboard/dashboard.service.ts
> +                    dimensions.height += mouseY;
Indentation issue.

2021-06-02 13:22 UTC, donna-marijne commented on src/components/dashboard/dashboard.service.ts
> +
Remove excess newlines.

2021-06-02 13:24 UTC, donna-marijne commented
@JonathanToddMF As previously discussed, we have reached the limit of time that I'm willing to spend on this, so if the above changes can't be completed before the end of the day, let me know.

2021-06-02 14:20 UTC, JonathanToddMF commented
Hey @donna-marijne all one of the above changes are fixed. The only remaining issue is that of specifying the col and row for the pinned widget. I think I should be able to resolve this before EOD.

2021-06-03 09:07 UTC, donna-marijne reviewed
I've started a review, but noticed another issue.
https://plnkr.co/edit/2tWjk1ufPHwzWL60
[![Image from Gyazo](https://i.gyazo.com/c0f33aaedc40f906b698302544bd309c.gif)](https://gyazo.com/c0f33aaedc40f906b698302544bd309c)

Unfortunately it's time to shelve this feature. Please keep the branch around, if we get to the bottom of the current backlog then we can come back to this.

2021-06-03 09:08 UTC, closed without merging