EL-4237: Standalone Navigation: option to disable navigation links
UXAspects/UXAspects pull request #1544
Opened 2021-06-02 13:44 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-4237

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2021-06-02 13:50 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4237-standalone-nav-disable-links~CI

2021-06-03 14:01 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4237-standalone-nav-disable-links

2021-06-04 10:41 UTC, donna-marijne requested changes
Thanks for the changes. I noticed a couple of issues:

1. It's using the 'no-drop' cursor, which we decided to stop using for disabled items.
2. The expander icon does not share the disabled appearance.
    ![image](https://user-images.githubusercontent.com/26114101/120788941-d6eaae00-c528-11eb-83e4-0174af65a04d.png)
3. Disabled items can receive focus and expand using the keyboard.
    [![Image from Gyazo](https://i.gyazo.com/800348db30729e935f77ae6f76608a19.gif)](https://gyazo.com/800348db30729e935f77ae6f76608a19)

https://plnkr.co/edit/yusqSJVqQdi8Noh7

A general tip for e2e tests, maybe you do this already: after writing them, temporarily back out your component fix and make sure that all of the new tests fail.

2021-06-04 10:41 UTC, donna-marijne commented on e2e/tests/components/navigation/navigation.e2e-spec.ts
> +        expect(await page.isItemDisabled(children[0])).toBeTruthy();
```suggestion
        expect(await page.isItemDisabled(children[0])).toBe(true);
```
It doesn't matter in this context, but as a rule I recommend that you never use "fuzzy logic" in automated tests. Assert the exact value that you expect.

2021-06-04 10:41 UTC, donna-marijne commented on e2e/tests/components/navigation/navigation.e2e-spec.ts
> +        browser.actions().mouseMove(items[3]).click();
This is async, so you probably need to `await`.

2021-06-07 09:59 UTC, donna-marijne requested changes
Thanks, there should also be test coverage for disabled items in the "tree" mode.

Any time you fix an issue, including during code review, you should consider adding test coverage for it.

2021-06-07 14:57 UTC, JonathanToddMF commented
Thanks for the feedback Donna.

I have added tests to cover tree mode, focus and child nodes.

I also removed the 2 duplicated screenshots and added additional screenshot coverage of tree mode, focus and child nodes

2021-06-07 14:57 UTC, JonathanToddMF commented
Waiting on build passing before re-requesting review

2021-06-08 14:38 UTC, donna-marijne commented
Great, thank you, this test coverage is good.

2021-06-11 09:19 UTC, donna-marijne approved these changes

2021-06-11 09:19 UTC, merged