EL-4241: Date Range Picker: "Missing locale data" error
UXAspects/UXAspects pull request #1545
Opened 2021-06-04 09:46 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4241

#### Description of Proposed Changes

Injected LOCALE_ID into the date-formatter-pipe.ts and based this as the third parameter in formatDate

#### Documentation CI URL

#### Downstream Build(s)

2021-06-04 09:47 UTC, JonathanToddMF commented
Build Link - https://jenkins.swinfra.net/job/SEPG/job/UXAspects/view/Developer/job/UXAspects~UXAspects~EL-4241-date-range-picker-locale-data~CI/

2021-06-04 12:59 UTC, JonathanToddMF commented
Languages checked:

- German
- French
- Spanish
- Hindi
- Arabic
- Polish

2021-06-04 13:02 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4241-date-range-picker-locale-data~CI

2021-06-07 09:29 UTC, donna-marijne requested changes
Looks good. We generally prefix private properties with an underscore in this project.

2021-06-07 09:29 UTC, donna-marijne commented on src/pipes/date-formatter/date-formatter.pipe.ts
> +    constructor(@Inject(LOCALE_ID) private locale: string) { }
```suggestion
    constructor(@Inject(LOCALE_ID) private _locale: string) { }
```

2021-06-08 09:49 UTC, donna-marijne approved these changes
Verification (repro steps from https://portal.digitalsafe.net/browse/EL-4241):
1. https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4241-date-range-picker-locale-data/#/components/date-time-picker#date-range-picker - :heavy_check_mark:
2. https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-4241-date-range-picker-locale-data/#/ui-components/input-controls#date-range-picker - :heavy_check_mark:

2021-06-08 14:04 UTC, Roland-Penny approved these changes
Looks good. Accepted

2021-06-08 14:11 UTC, merged