EL-4202: Column Picker plunker example doesn't compile
UXAspects/UXAspects pull request #1554
Opened 2021-06-25 10:38 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4202

#### Description of Proposed Changes

Added string | ColumnPickerGroupItem to doc snippet

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2021-06-25 10:41 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4202-column-picker-doesnt-compile) to go ahead and create the build...

2021-06-25 10:45 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4202-column-picker-doesnt-compile~CI

2021-06-25 11:15 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4202-column-picker-doesnt-compile

2021-06-28 09:33 UTC, donna-marijne requested changes
Please fill in the PR template. Use the user script if you are having trouble with this, it is one click.

2021-06-28 09:33 UTC, donna-marijne commented on docs/app/pages/components/components-sections/tables/column-picker/snippets/app.ts
> +import { ColumnPickerGroupItem } from '../../../../../../../../src/components/table/column-picker/interfaces/column-picker-group-item.interface';
Import from @ux-aspects/ux-aspects, applications do not have access to our src directory.

2021-06-29 10:41 UTC, donna-marijne commented
Please update the PR description.

2021-06-30 08:41 UTC, donna-marijne requested changes

2021-06-30 08:41 UTC, donna-marijne commented on docs/app/pages/components/components-sections/tables/column-picker/snippets/app.ts
> +import { ColumnPickerGroupItem } from '@ux-aspects/ux-aspects/components/table/column-picker/interfaces/column-picker-group-item.interface';
Import this from @ux-aspects/ux-aspects, just like you would in an application (see the line above).

2021-07-01 08:52 UTC, donna-marijne approved these changes
Verification:

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4202-column-picker-doesnt-compile/#/components/tables#column-picker - :heavy_check_mark:

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-4202-column-picker-doesnt-compile/#/ui-components/tables#column-picker - :heavy_check_mark:

2021-07-01 09:18 UTC, ashley-hunter approved these changes
All good, thank you

2021-07-01 09:18 UTC, merged