EL-4252 - Menu: close menu when focus leaves the trigger button
UXAspects/UXAspects pull request #1564
Opened 2021-07-27 12:58 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4252

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4252-menu-close-menu-when-lose-focus

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4252-menu-close-menu-when-lose-focus~CI/)

2021-07-27 12:59 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=EL-4252-menu-close-menu-when-lose-focus) to go ahead and create the build...

2021-07-27 13:03 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-4252-menu-close-menu-when-lose-focus~CI

2021-07-27 13:32 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4252-menu-close-menu-when-lose-focus

2021-07-30 08:24 UTC, donna-marijne requested changes
Thanks for the change. Looks like there is an issue with submenus when accessing via the keyboard.

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4252-menu-close-menu-when-lose-focus/#/components/buttons#dropdowns

1. Tab to the menu button.
2. Press enter.
3. Press right arrow.

The menu should not collapse. Could you add test coverage for this case?

After blur, if you walk the ancestors of `document.activeElement` and you don't find the class `ux-menu` you can conclude that focus has exited the menu tree.

2021-07-30 08:24 UTC, donna-marijne commented on src/components/menu/menu-trigger/menu-trigger.directive.ts
> +    private checkFocus(): boolean {
```suggestion
    private hasFocus(): boolean {
```

2021-07-30 08:24 UTC, donna-marijne commented on src/components/menu/menu-trigger/menu-trigger.directive.ts
> +            timer(this._debounceTime)
I think `setTimeout` might be more efficient.

2021-08-02 08:34 UTC, donna-marijne requested changes
Thanks Jonathan, it works well. After using it for a bit, I think there is some risk in making this the default behavior, so let's add a `closeOnFocus` input to enable this feature.

2021-08-02 08:34 UTC, donna-marijne commented on e2e/pages/app/menu/menu.testpage.component.ts
> +    placement$: BehaviorSubject<string> = new BehaviorSubject<string>('right');
Not clear why this was changed.

2021-08-02 08:34 UTC, donna-marijne commented on e2e/tests/components/menu/menu.e2e-spec.ts
> +        await browser.sleep(500);
Presumably this should be removed.

2021-08-02 08:34 UTC, donna-marijne commented on e2e/tests/components/menu/menu.e2e-spec.ts
> +            expect(await element(by.className('ux-menu')).isPresent()).toBe(true);
Should probably check that the submenu is present as well.

2021-08-02 08:34 UTC, donna-marijne commented on src/components/menu/menu-trigger/menu-trigger.directive.ts
> +    /** Check whether the overlay or button has focus */
This now only checks the overlay, so the comment (and probably function name) needs updating.

2021-08-02 08:34 UTC, donna-marijne commented on src/components/menu/menu-trigger/menu-trigger.directive.ts
> +                console.log(this.hasFocus());
Remove this.

2021-08-02 08:34 UTC, donna-marijne commented on e2e/pages/app/menu/menu.testpage.component.html
> +    <ux-menu #MenuItemMenu menuClass="mark-as-menu">
```suggestion
    <ux-menu #markAsMenu menuClass="mark-as-menu">
```
The convention for property names is to use initial lowercase - check the documentation example.

2021-08-02 08:34 UTC, donna-marijne commented on e2e/tests/components/filters/filters.e2e-spec.ts
> +        await page.clickOnAuthorMenu();
After adding the setting, these changes can be removed.

2021-08-03 10:21 UTC, donna-marijne requested changes
The setting probably needs to be on the trigger button rather than the menu, because `closeOnBlur="true"` could be set on a submenu only and this code would not handle that (I'm not even sure what the expected behavior would be in that case).

You should also coerce boolean inputs.

2021-08-03 10:21 UTC, donna-marijne commented on e2e/tests/components/menu/menu.e2e-spec.ts
> +            // check menu closed
This comment is not correct, remove or update.

2021-08-03 10:21 UTC, donna-marijne commented on e2e/tests/components/menu/menu.e2e-spec.ts
> +        it('should not close the menu when the tabbed away from the menu', async () => {
```suggestion
        it('should not close the menu when tabbed away from the menu', async () => {
```

2021-08-03 10:21 UTC, donna-marijne commented on e2e/tests/components/menu/menu.e2e-spec.ts
> +        it('should close the menu when the tabbed away from the menu', async () => {
```suggestion
        it('should close the menu when tabbed away from the menu', async () => {
```

2021-08-03 14:00 UTC, donna-marijne approved these changes
Verification:

https://plnkr.co/edit/BWsWIqbLLMjocXKC (open source) - :heavy_check_mark:
https://plnkr.co/edit/pCSS78fHQqSQFdir (Micro Focus) - :heavy_check_mark:

2021-08-04 09:43 UTC, Roland-Penny approved these changes
Accepted based on dev QA feedback

2021-08-04 09:56 UTC, merged