EL-4277 - Combobox: Issue with combox controls and custom validators
UXAspects/UXAspects pull request #1596
Opened 2021-10-29 15:40 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4277

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4277-combobox-validators

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4277-combobox-validators~CI/)

2021-11-02 09:10 UTC, donna-marijne requested changes
Based on testing the given repro example, this does not seem to resolve the problem.
[![Image from Gyazo](https://i.gyazo.com/c31633da65ee903ff4a37641fe472665.gif)](https://gyazo.com/c31633da65ee903ff4a37641fe472665)

Additionally as seen above, the value appears briefly in red, which is not desirable.

2021-11-02 09:10 UTC, donna-marijne commented on src/components/select/select.component.spec.ts
> +        </span>
This is a unit test, so you don't need to render and and extract values from the DOM to test.

2021-11-02 09:10 UTC, donna-marijne commented on src/components/select/select.component.spec.ts
> +        console.log('file: select.component.spec.ts ~ line 1013 ~ fit ~ input', input);
This should be removed.

2021-11-02 09:10 UTC, donna-marijne commented on src/components/select/select.component.spec.ts
> +export class SelectNullValueTestComponent {
This issue is about the required validator, maybe a more accurate name can be chosen.

2021-11-02 16:25 UTC, JonathanToddMF commented
> Based on testing the given repro example, this does not seem to resolve the problem. [![Image from Gyazo](https://camo.githubusercontent.com/b1b1efed7ade1714c2aa0df8de8396f93d145be9978995f16bd7ea6c5e12d1bf/68747470733a2f2f692e6779617a6f2e636f6d2f63333136333364613635656539303366663461333736343166653437323636352e676966)](https://gyazo.com/c31633da65ee903ff4a37641fe472665)
> 
> Additionally as seen above, the value appears briefly in red, which is not desirable.

Hey Donna, I noticed something about their example plunker which isn't correct. I have detailed the issue in a response to Vadim here - https://teams.microsoft.com/l/message/19:f9c3e360e0454784a9fb04c49f04ea65@thread.skype/1635870242326?tenantId=856b813c-16e5-49a5-85ec-6f081e13b527&groupId=51fc2a42-4497-4231-baca-19348d1ef830&parentMessageId=1634891721057&teamName=%23ux-aspects&channelName=General&createdTime=1635870242326

The colour appearing briefly in red is still an issue I am working to resolve.

2021-11-03 11:27 UTC, JonathanToddMF commented
Hi @donna-marijne, I have been looking at the issue regarding the red colour and can't seem to find a way to resolve it. There seems to be a delay before the ng-invalid class is removed. There doesn't seem to be any timers or delays in the code which would introduce this. Unless I am missing something? 

Any help would be appreciated!

2021-11-24 13:38 UTC, donna-marijne requested changes
Documentation resolution:
- Add a note to the `disabled` and `required` inputs that they should not be used within a form.
- Add some example code under a new header showing how to use the `required` validator within a form. There is an example of form validation in the [Text Input](https://pages.github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/#/ui-components/input-controls#raised-text-input) documentation.

2021-12-15 12:51 UTC, JonathanToddMF commented
Closing this as the branch isn't the same name as the ux-aspects-micro-focus branch

2021-12-15 12:51 UTC, closed without merging