El-4288 - Angular 13
UXAspects/UXAspects pull request #1598
Opened 2021-11-10 13:49 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/El-4288

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_El-4288-angular-13

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~El-4288-angular-13~CI/)

2021-11-12 15:29 UTC, JonathanToddMF commented
Hi @donna-marijne, I think I have updated most of the current dependencies and when running npm run start I am getting a few errors of "One or more import cycles would need to be created to compile this component, which is not supported by the current compiler configuration."

I am not sure if this is something that needs updated as part of the angular 13 update or is something I have missed. Any advice on this would be great, maybe running npm run start at this stage isn't the correct way to test at this stage?

2021-11-15 10:28 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=El-4288-angular-13) to go ahead and create the build...

2021-11-15 12:07 UTC, ashley-hunter commented
Thanks Jonathan, I am getting quite a few errors when I try to run `npm start` which is to be expected. As of Angular 13 View Engine is no longer supported, so I don't believe there is a way for us to easily continue support Angular 11 either which required libraries to be shipped in the View Engine format. As of recently Angular's approach is now deprecate in one major version and remove in the next major version, which means we likely will only be able to support 2 versions of Angular going forward rather than the 3 we previously did. This aligns with how we do it in Universal too.

To fix the errors you need to tell Angular to build the library in the Ivy `partial` format. In the `tsconfig-build.json` file you need to remove `"enableIvy": false` and add `"compilationMode": "partial"` instead.

You will also likely get some errors complaining about `.mjs` files, so you will need to update the webpack configs to add that as a possible extension (note we should also now be able to remove the `rxAlias` that was in the resolve section before):

```javascript
resolve: {
        extensions: ['.ts', '.js', '.mjs'],
},
```

And then update the `rules` section to include the following rule:

```javascript
{
    test: /\.m?js/,
    resolve: {
        fullySpecified: false
    }
},
```

Angular 13 has also dropped support for IE 11. While this shouldn't effect people consuming our library (if they are using Angular 12), we can probably now remove the `// Downlevel Angular Packages` section from our webpack config as this was required to support IE11, but if we are using Angular 13 we can't support IE 11 anyway.

There may be additional Webpack config changes required, I haven't checked, but for reference you can see the configuration the Angular CLI uses here which may be useful as a reference:

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/configs/common.ts

2021-11-16 10:31 UTC, ashley-hunter commented
Hey @JonathanToddMF, I pushed a fix for all the NG3003 errors that were appearing on serve. Hopefully that will help you out a bit.

2021-11-16 10:32 UTC, JonathanToddMF commented
Thanks @ashley-hunter!

2021-12-01 11:29 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~El-4288-angular-13~CI

2021-12-01 14:40 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_El-4288-angular-13

2021-12-02 15:34 UTC, donna-marijne requested changes
Initial verification results:

This page hangs the browser tab (Firefox and Chrome on Windows):
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_El-4288-angular-13/#/showcase/visualizations/partition-map

Hierarchy bar icons are missing (also affects org chart example):
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_El-4288-angular-13/#/components/hierarchy-bar

Otherwise works well. Code review to follow.

2021-12-02 15:36 UTC, ashley-hunter commented
Thanks Donna, the partition map showcase issue is a pre-existing issue. I will look into the missing icons, thanks!

2021-12-03 15:47 UTC, donna-marijne requested changes
Thanks for the intense work to revise the build for this project. I have added some comments. Not quite clear on the removal of IE11 at this point. If someone has set up an Angular 12 app for IE11 I would expect them to be able to deploy UX Aspects.

I noticed that some auto formatting has been applied to affected files, but I was not able to determine which tool has been configured for this. If we do apply formatting, I would prefer that it uses the same rules that we use in Universal.

2021-12-03 15:47 UTC, donna-marijne commented on src/styles/ux-aspects.less
> +// CDK Classes for using AutoFillMonitor
Looks like these comments got moved in a misleading way.

2021-12-03 16:19 UTC, ashley-hunter commented
Thanks for the feedback Donna, I'll restore the IE content, that was an oversight on my part.

As for the formatting changes, that was probably due to my editor setup using universal. You mention you'd like it to be consistent with Universal, would you like me to bring in prettier with the same config? I realise we didn't do this before because it can make git blame harder, but if you think now is an acceptable time to set it up I can easily add it in?

2021-12-03 16:47 UTC, donna-marijne commented
Thanks Ashley. If it's easy enough to do, you could bring in a prettier config to make sure that formatting is consistent when it is done. Not sure about adding the git hook though, maybe we can leave it as a manual step for a while and see how it goes.

2021-12-03 16:58 UTC, JonathanToddMF commented
Just to add to the above, I have spent a good portion of the day going through most of the common commands that I use when making changes to the repo and can't find anything other than the missing icons mentioned above. I will look through the code base for anything I notice.

Thanks again Ashley for the work put into this, should make things a lot easier going forward.

2021-12-09 11:32 UTC, ashley-hunter commented
@donna-marijne I have updated the package.json to make chart.js and ng-2charts peer dependencies with a restriction so the version is <3. This should prevent the issue you were seeing from arising.

2021-12-09 17:25 UTC, donna-marijne approved these changes
Tested documentation and in standalone Angular 12 and 13 projects, all looks good to me.

2021-12-10 10:10 UTC, merged