EL-4277 - fixing pr
UXAspects/UXAspects pull request #1601
Opened 2021-12-15 12:49 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4277

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4277-validation-docs

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4277-validation-docs~CI/)

2021-12-15 12:50 UTC, JonathanToddMF commented
Old PR link - https://github.com/UXAspects/UXAspects/pull/1596

2021-12-15 13:17 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4277-validation-docs

2021-12-15 16:13 UTC, ashley-hunter requested changes
Thanks, looks good, just had two minor suggestions for consistency.

2021-12-15 16:13 UTC, ashley-hunter commented on docs/app/pages/components/components-sections/select/select/snippets/validation.ts
> +	ngOnInit() {
```suggestion
	ngOnInit(): void {
```

2021-12-15 16:13 UTC, ashley-hunter commented on docs/app/pages/components/components-sections/select/select/snippets/validation.ts
> +	private _onDestroy = new Subject<void>();
```suggestion
	private _onDestroy$ = new Subject<void>();
```

2021-12-16 11:57 UTC, ashley-hunter requested changes
Thanks, looks good and seems to work well, I just had one final suggestion to include the Component decorator just so someone can easily copy and paste the example code into plunker or a file without having to modify it. It caught me out when I went to check it in plunker so its possible others might have the same issue. Apart from that, all good.

2021-12-16 11:57 UTC, ashley-hunter commented on docs/app/pages/components/components-sections/select/select/snippets/validation.ts
> +export class AppComponent implements OnInit, OnDestroy {
```suggestion
import { OnDestroy, OnInit, Component } from '@angular/core';
import {
	AbstractControl, 
	FormControl,
	FormGroup,
	Validators
} from '@angular/forms';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
    selector: 'app',
    templateUrl: './app.component.html'
})
export class AppComponent implements OnInit, OnDestroy {
```

2021-12-16 14:00 UTC, ashley-hunter submitted a review, later dismissed
All good, thanks

2022-01-05 10:45 UTC, JonathanToddMF commented
Just adding you @donna-marijne for consistency with the inner source pr

2022-01-05 13:29 UTC, donna-marijne requested changes

2022-01-05 13:29 UTC, donna-marijne commented on docs/app/pages/components/components-sections/select/select/select.component.html
> +    other angular form element.
```suggestion
    other Angular form element.
```

2022-01-05 13:29 UTC, donna-marijne commented on docs/app/pages/components/components-sections/select/select/select.component.html
> +    Forms API to achieve this instead.
Link to the documentation of the API mentioned.

2022-01-05 13:29 UTC, donna-marijne commented on docs/app/pages/components/components-sections/select/select/snippets/validation.html
> +    </div>
Remove the checkbox to simplify the example, the intent is to show how to apply validation to the select component only.

2022-01-10 09:24 UTC, donna-marijne approved these changes

2022-01-10 09:24 UTC, merged