382091 - Dropdown Menu: Tabbing issues
UXAspects/UXAspects pull request #1618
Opened 2022-01-27 16:24 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=382091

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_382091-dropdown-menu-tabbing

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~382091-dropdown-menu-tabbing~CI/)

2022-01-31 10:16 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~382091-dropdown-menu-tabbing~CI

2022-01-31 10:40 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_382091-dropdown-menu-tabbing

2022-02-01 10:24 UTC, donna-marijne requested changes
This only seems to solve one of the points noted in the ticket. Focus does not progress to the next item in the tab ring.
![menu-focus](https://user-images.githubusercontent.com/26114101/151950937-1afddec1-a604-451d-b82d-41c4365c38a0.gif)

2022-02-01 10:24 UTC, donna-marijne commented on src/components/menu/menu/menu.component.ts
> +        if (event.keyCode === TAB) {
Use the blur event instead of listening for a tab key. Some screen readers use other keys as well as tab to change focus.

2022-02-07 15:19 UTC, JonathanToddMF commented
Hey @donna-marijne I have done some refactoring on this. Just one thing I have noticed about the above gif you included. Is this using the same menu for each of the buttons? I believe this is what is causing the issue. Removing the same menu trigger for the other buttons seems to fix the issue. I think the same instance of the trigger is causing it to go to the next tab item which would be the plunker iframe in this example. 

If you have another button that isn't using the same menu trigger it fixes the issue. I don't believe there would be a scenario in which there would be two buttons opening the same menu beside each other? Here is a plunker to demonstrate - https://plnkr.co/edit/nAYn3LKv3Z2OuuA7

2022-02-07 15:24 UTC, donna-marijne commented
I believe it was a slightly modified version of our documentation example.

2022-02-07 16:35 UTC, JonathanToddMF commented
I did some playing around with this. I managed to solve the issue.

2022-02-08 10:50 UTC, donna-marijne requested changes
Thanks, it seems to work well. Could you revert the changes to the existing e2e tests, since the changes alter the nature of the tests.

2022-02-08 10:50 UTC, donna-marijne commented on src/components/menu/menu/menu.component.ts
> +        this._keyManager.tabOut.complete();
I don't think this is appropriate, you didn't create this observable so you should not terminate it.

2022-02-08 12:12 UTC, JonathanToddMF commented
Hi @donna-marijne with regards to the e2e test changes. These changes mixed with the space bar fix fail the original tests.

Originally these were to test when the menu trigger loses focus when the menu was open, but because the space bar now focuses the first menu item and tabbing away from the menu it will close it, this breaks one of the tests. I changed the tests to a click as it doesn't focus the first item in the list.

Although, looking at the documentation for closeOnBlur - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_382091-dropdown-menu-tabbing/#/components/buttons#dropdowns - we have it listed for when the menu loses focus, although the closeOnBlur doesn't cover the requirements in this ticket, the code changes in this PR work better than the original closeOnBlur implementation. 

Perhaps these changes should replace the current closeOnBlur functionality?

2022-02-09 11:23 UTC, donna-marijne commented
Hi Jonathan, just want to be a bit careful about this so that we don't revert a fix that was done relatively recently for someone.

I think this is the relevant ticket:
https://internal.almoctane.com/ui/?p=131002/7002#/entity-navigation?entityType=work_item&id=373244

Important to note that in the described scenario of EL-4252, tab is not moving focus away from the trigger button but rather the menu itself. This is because pressing space on the trigger moves focus to the first menu item. The title of the ticket is misleading, which is my fault.

This current request and EL-4252 seem to be complimentary: the menu should optionally close when tabbing out (obeying closeOnBlur), and the next focus target should be the focusable element that comes after the trigger in the normal tab sequence.

In terms of implementation, it's fine to change the inner workings of existing behavior, as long as the e2e tests which are already in place continue to pass without modification.

2022-02-14 15:30 UTC, donna-marijne requested changes
Thanks, make sure to update relevant comments so that they remain accurate when you make changes.

2022-02-14 15:30 UTC, donna-marijne commented on src/components/menu/menu/menu.component.ts
> +    setCloseOnBlur(closeOnBlur: boolean): void {
This doesn't need a parameter, you are checking the value of closeOnBlur twice.
```
        if (this.closeOnBlur) {
            this.menu.setCloseOnBlur(this.closeOnBlur);
        }
```

2022-02-16 14:37 UTC, donna-marijne approved these changes
Verification:
https://plnkr.co/edit/qicO2cPmqiywgll2 - :heavy_check_mark:
https://plnkr.co/edit/q6Skm4pXdSE4FhHH - :heavy_check_mark:

2022-02-16 14:37 UTC, merged