412025 - Add prominent links to the #ux-aspects channel
UXAspects/UXAspects pull request #1638
Opened 2022-03-15 13:22 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=412025

#### Description of Proposed Changes

- Removed blog and replaced with Get help in masthead
- Removed blog and added teams link to Get Involved section

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_412025-prominent-link-to-teams-channel

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~412025-prominent-link-to-teams-channel~CI/)

2022-03-15 13:27 UTC, JonathanToddMF commented
Hi @Roland-Penny as discussed here are the 3 examples I came up with for the new Get Involved section

Replaced with new colourful icons
![screencapture-localhost-1](https://user-images.githubusercontent.com/57634621/158387108-7cc31a79-ca4f-4757-955d-e5d50b604eae.png)

Replaced colourful icons smaller
![screencapture-localhost-2](https://user-images.githubusercontent.com/57634621/158387099-3a30d22c-9ec1-4bde-ad2e-6523ab393ab4.png)

No icons
![screencapture-localhost-3](https://user-images.githubusercontent.com/57634621/158387089-a047108b-8747-410d-8e67-386937383503.png)

Personally I think the first one is fine with the icons being the same size as the others. 

@donna-marijne do you have any opinion on this? Roland and I spoke about replacing the twitter icon with a similar Teams icon but unfortunately their icon uses multiple colours and isn't one solid colour. So we discussed replacing these icons with the colourful variants.

2022-03-15 14:34 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~412025-prominent-link-to-teams-channel~CI

2022-03-16 11:51 UTC, donna-marijne requested changes

2022-03-16 14:26 UTC, JonathanToddMF commented on docs/app/components/navigation-bar/navigation-bar.component.html
> +        </ng-container>
Makes sense, is there a way to have an external url with the routerLink? I was having some trouble getting it to work.

2022-03-16 14:30 UTC, donna-marijne commented on docs/app/components/navigation-bar/navigation-bar.component.html
> +        </ng-container>
I would suggest extending the JSON schema with an optional `href` property which can be used for external links.

2022-03-21 11:34 UTC, JonathanToddMF commented on docs/app/components/navigation-bar/navigation-bar.component.html
> +        </ng-container>
`<a class="navigation-bar-item"
           *ngFor="let link of social"
           [routerLink]="link.link"
           [attr.href]="link.href"
           routerLinkActive="active">
           {{ link.title }}
</a>`

Was kind of hoping the following would work but there doesn't seem to be a way to conditionally turn off the routerLink. Unless you have any ideas? Maybe a custom directive but unsure if that is worth it for this implementation?

2022-03-21 11:49 UTC, donna-marijne commented on docs/app/components/navigation-bar/navigation-bar.component.html
> +        </ng-container>
```html
<a *ngIf="link.link" [routerLink]="link.link" ...>{{ link.title }}</a>
<a *ngIf="!link.link" [href]="link.href" ...>{{ link.title }}</a>
```

Unfortunately the Angular directives are badly designed in this regard, and force you to duplicate code.

2022-03-22 16:01 UTC, donna-marijne requested changes
Thanks, it looks good, code needs a bit of a cleanup.

2022-03-22 16:01 UTC, donna-marijne commented on docs/app/components/navigation-bar/navigation-bar.component.ts
> +    help: ILink[] = this.navigation.help;
Not seeing where this is used.

2022-03-23 13:49 UTC, donna-marijne approved these changes
Verification:

Blog and Twitter link removed:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_412025-prominent-link-to-teams-channel/#/landing - :heavy_check_mark:

Blog and Twitter link removed; MS Teams links added:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_412025-prominent-link-to-teams-channel/#/landing - :heavy_check_mark:

2022-03-23 14:19 UTC, Roland-Penny approved these changes
Looks good

2022-03-23 14:26 UTC, merged