543001 - infinite scroll load function
UXAspects/UXAspects pull request #1674
Opened 2022-09-01 10:40 UTC by JonathanToddMF

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=543001

#### Description of Proposed Changes

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_543001-infiniteScroll-load-function

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~543001-infiniteScroll-load-function~CI/)

2022-09-01 20:38 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=543001-infiniteScroll-load-function) to go ahead and create the build...

2022-09-02 12:53 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~543001-infiniteScroll-load-function~CI

2022-09-02 13:22 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_543001-infiniteScroll-load-function

2022-09-06 08:44 UTC, donna-marijne requested changes
Looks good. An e2e test might be more appropriate to this issue.

2022-09-06 08:44 UTC, donna-marijne commented on src/directives/infinite-scroll/infinite-scroll.component.spec.ts
> +    it('should resolve the load function when reset is called during load', () => {
It doesn't look like reset is called during load (or indeed at all).

2022-09-06 08:44 UTC, donna-marijne commented on src/directives/infinite-scroll/infinite-scroll.component.spec.ts
> +        component.infiniteScrollDirective.check();
In the repro sandbox, they are only calling `reset()` without an argument and without calling `check`.
```
this.usersList.reset();
```
Could you add a test case which matches this scenario?

2022-09-09 12:58 UTC, donna-marijne approved these changes
Verification:
https://codesandbox.io/s/infinite-scroll-ux-aspects-micro-focus-forked-dtifcv?file=/package.json - :heavy_check_mark:

2022-09-09 13:15 UTC, Roland-Penny approved these changes
Looks good

2022-09-09 13:16 UTC, merged