D3 Upgrade
UXAspects/UXAspects pull request #1681
Opened 2022-10-13 09:03 UTC by JonathanToddMF

#### Checklist

* [ ] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [ ] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [ ] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

#908 

#### Description of Proposed Changes

upgraded d3 to version 7
updated organisational chart

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2022-10-13 16:29 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=issue-908-d3-upgrade) to go ahead and create the build...

2022-10-14 09:48 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~issue-908-d3-upgrade~CI

2022-10-14 14:07 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_issue-908-d3-upgrade

2022-10-19 10:54 UTC, donna-marijne requested changes
Thanks Jonathan, upgrade looks good. However this appears to be a breaking change, so it needs to be part of our next major version increment.

2022-10-19 10:54 UTC, donna-marijne commented on protractor.conf.js
> +        './e2e/tests/components/organization-chart/*.e2e-spec.ts'
I guess this was not intended to be committed.

2022-10-19 13:34 UTC, ashley-hunter commented
> Thanks Jonathan, upgrade looks good. However this appears to be a breaking change, so it needs to be part of our next major version increment.

I don't think this is a breaking change, unlike most third party libraries we use, d3 is listed under `dependencies` and not `peerDependencies`, so we are in control of the version that our components use. The root application can install a different version of D3 should they wish but our components will still use 7.x.x. This could result in some code duplication in the applications bundle as it may be bundling two versions of some D3 functions, but it means it is not a breaking change.

2022-10-19 13:40 UTC, donna-marijne commented
Hmm, I'm seeing some changed callback signatures, presumably that's going to behave differently depending on which version of d3 the application has installed.
![image](https://user-images.githubusercontent.com/26114101/196707381-6511b63a-f687-4c07-8f6f-61c93f536b5d.png)

(Unless we do some detection and handle them differently depending on which version of d3 we are dealing with of course, which I believe is the plan.)

2022-10-19 13:46 UTC, ashley-hunter commented
> Hmm, I'm seeing some changed callback signatures, presumably that's going to behave differently depending on which version of d3 the application has installed.

That would be the case if D3 was listed as a peer dependency, but it is a dependency so it doesn't matter what version the application has installed (the application may not even have it installed).

If an application is currently using D3 v6 node_modules would look like this:

- node_modules
  + d3 (v6)
  + @ux-aspects/ux-aspects
      + d3 (v7)

If the application has d3 v7 installed or no version of D3 installed the node_modules would look like this:

- node_modules
  + d3 (v7)
  + @ux-aspects/ux-aspects

In either case, our components are going to use D3 v7 and the application will use whatever version is in the top level node_modules folder. So different signatures will have no effect on the application as it can use a different version of D3 than our components.

2022-10-19 13:46 UTC, ashley-hunter commented
> Hmm, I'm seeing some changed callback signatures, presumably that's going to behave differently depending on which version of d3 the application has installed.

That would be the case if D3 was listed as a peer dependency, but it is a dependency so it doesn't matter what version the application has installed (the application may not even have it installed).

If an application is currently using D3 v6 node_modules would look like this:

- node_modules
  + d3 (v6)
  + @ux-aspects/ux-aspects
      + d3 (v7)

If the application has d3 v7 installed or no version of D3 installed the node_modules would look like this:

- node_modules
  + d3 (v7)
  + @ux-aspects/ux-aspects

In either case, our components are going to use D3 v7 and the application will use whatever version is in the top level node_modules folder. So different signatures will have no effect on the application as it can use a different version of D3 than our components.

2022-10-19 13:48 UTC, ashley-hunter commented
> Never mind, I misread your comment. It's worth checking for sure. As long as d3 doesn't have any globals like some of those old libraries tend to.

Very true, worth checking!

2022-10-19 15:28 UTC, JonathanToddMF commented
@donna-marijne and @ashley-hunter had a look through v5/6 of D3 and there aren't any global assignments

2022-10-20 10:58 UTC, JonathanToddMF commented
Put together a quick example in codeSandBox looks good to me. 

Using d3 version 5 to create a simple bar chart below the organization chart - https://codesandbox.io/s/organization-chart-ux-aspects-micro-focus-forked-o1t5ns?file=/src/app/app.component.ts:5567-5572

2022-10-20 12:47 UTC, donna-marijne approved these changes
Looks good, thank you for checking.

2022-10-20 12:47 UTC, merged