Defect/facet drag n drop
UXAspects/UXAspects pull request #1728
Opened 2024-02-19 16:44 UTC by AndrewCochrane24

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

Facet drag and drop feature didn't work, either dragging across one row or multiple.

#### Description of Proposed Changes

Added solution that addresses this.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_

#### Downstream Build(s)

2024-02-19 16:45 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://jenkins.swinfra.net/job/SEPG/job/New%20SEPG%20Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=UXAspects&REPO_NAME=UXAspects&BRANCH_NAME=defect/facet-drag-n-drop) to go ahead and create the build...

2024-02-19 16:47 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~defect%20%E2%81%84%20facet-drag-n-drop~CI

2024-02-19 17:07 UTC, JonathanToddMF reviewed
Hey @AndrewCochrane24 looks like we are getting some linting errors in the build

https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~defect%20%E2%81%84%20facet-drag-n-drop~CI/

2024-02-20 12:30 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_defect--facet-drag-n-drop

2024-02-21 11:21 UTC, JonathanToddMF requested changes
Hey @AndrewCochrane24 great work on this, the only slight thing I am noticing is this slightly odd styling when grabbing a facet and moving the mouse slightly.

[![Image from Gyazo](https://i.gyazo.com/91434c209bbbbe01aa4a589378433e71.gif)](https://gyazo.com/91434c209bbbbe01aa4a589378433e71)

You may also notice I added a downstream build to the PR, this builds after the open source builds and runs the build for the internal version of the library. The internal library imports a lot of the components from the open source library (you have to manually start it, I can kick it off for you if you push any updates). The facet-container works and looks well in there too. Just with the same odd styling issue mentioned above.

https://pages.github.houston.softwaregrp.net/Inner-Source-Incubating/universal-codesandbox/#/editor?projectId=fc907941-8f20-421a-bc61-a2c9a6786191

2024-02-22 09:45 UTC, AndrewCochrane24 commented
> Hey @AndrewCochrane24 great work on this, the only slight thing I am noticing is this slightly odd styling when grabbing a facet and moving the mouse slightly.
> 
> [![Image from Gyazo](https://camo.githubusercontent.com/7fb1fb9d9d1b4c9c35e32e4813ca05fd077a1d1f1ba8fecb9b7bbb574dc47d49/68747470733a2f2f692e6779617a6f2e636f6d2f39313433346332303962626262653031616134613538393337383433336537312e676966)](https://gyazo.com/91434c209bbbbe01aa4a589378433e71) [ ![Image from Gyazo](https://camo.githubusercontent.com/7fb1fb9d9d1b4c9c35e32e4813ca05fd077a1d1f1ba8fecb9b7bbb574dc47d49/68747470733a2f2f692e6779617a6f2e636f6d2f39313433346332303962626262653031616134613538393337383433336537312e676966) ](https://gyazo.com/91434c209bbbbe01aa4a589378433e71) [ ](https://gyazo.com/91434c209bbbbe01aa4a589378433e71)
> 
> You may also notice I added a downstream build to the PR, this builds after the open source builds and runs the build for the internal version of the library. The internal library imports a lot of the components from the open source library (you have to manually start it, I can kick it off for you if you push any updates). The facet-container works and looks well in there too. Just with the same odd styling issue mentioned above.
> 
> https://pages.github.houston.softwaregrp.net/Inner-Source-Incubating/universal-codesandbox/#/editor?projectId=fc907941-8f20-421a-bc61-a2c9a6786191

Sorry for the late reply Jonathan, I'll fix this now.

2024-02-22 13:12 UTC, JonathanToddMF approved these changes
see below

2024-02-22 13:14 UTC, JonathanToddMF requested changes
Sorry, everything looks good. Just noticed some commented out code that can be removed

2024-02-22 13:14 UTC, JonathanToddMF commented on src/components/facets/facet-container.component.html
> +                    </div> -->
Remove the commented out code

2024-02-22 13:14 UTC, JonathanToddMF commented on src/components/facets/facet-container.component.less
> +    // background-color: orange;
here too

2024-02-22 15:00 UTC, AndrewCochrane24 commented on src/components/facets/facet-container.component.less
> +    // background-color: orange;
Done.

2024-02-22 15:00 UTC, AndrewCochrane24 commented on src/components/facets/facet-container.component.html
> +                    </div> -->
Done.

2024-02-27 09:04 UTC, merged